; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
platform_packages =
    platformio/framework-arduinoespressif8266 @ https://github.com/esp8266/Arduino.git

#lib_deps =
#    https://github.com/me-no-dev/ESPAsyncWebServer.git

build_flags = 
    -DPIO_FRAMEWORK_ARDUINO_LWIP_HIGHER_BANDWIDTH
    -DPIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK305
# default -DPIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_190703
#    -DPIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_191122
#    -DDEBUG_ESP_WIFI
#    -DDEBUG_ESP_CORE
#    -DDEBUG_ESP_PORT=Serial

upload_protocol = esptool
upload_port = /dev/ttyUSB0
upload_speed = 115200
upload_resetmethod = ck
upload_flags = 

board_build.flash_mode = qio
board_build.ldscript = eagle.flash.4m.ld

monitor_port = /dev/ttyUSB0
monitor_speed = 250000

debug_port = /dev/ttyUSB0
debug_speed = 250000
